n=input("enter a number ")
s= set()
s.add(int(n))
n= input("Enter a number :")
s.add(int(n))
n= input("Enter a number :")
s.add(int(n))
n= input("Enter a number :")
s.add(int(n))
n= input("Enter a number :")
s.add(int(n))
n= input("Enter a number :")
s.add(int(n))
n= input("Enter a number :")
s.add(int(n))
n= input("Enter a number :")
s.add(int(n))
print(s)